/**
 * @file test_symtable.c
 * @brief Quick test for symbol table (AVL tree)
 * @author GENERATED BY CHATGPT
 */

#include "../src/symtable.h"
#include <stdio.h>
#include <stdlib.h>

// Simple inorder print
void print_inorder(SNode *node) {
    if (!node)
        return;
    print_inorder(node->left);

    printf("Key: %s, ", node->key);
    switch (node->data->type) {
    case NODE_VAR:
        printf("VAR (type=%d, def=%d, init=%d)\n",
               node->data->data.var_data->data_type,
               node->data->data.var_data->defined,
               node->data->data.var_data->initialized);
        break;
    case NODE_FUNC:
        printf("FUNC (params=%d, def=%d)\n",
               node->data->data.func_data->param_count,
               node->data->data.func_data->defined);
        break;
    case NODE_GETTER:
        printf("GETTER (ret=%d, def=%d)\n",
               node->data->data.getter_data->return_type,
               node->data->data.getter_data->defined);
        break;
    case NODE_SETTER:
        printf("SETTER (param=%d, def=%d)\n",
               node->data->data.setter_data->param_type,
               node->data->data.setter_data->defined);
        break;
    }

    print_inorder(node->right);
}

int main(void) {
    SymTable table;
    symtable_init(&table);

    // Insert some variables
    symtable_insert(&table, "x", make_variable(TYPE_NUM, true, false));
    symtable_insert(&table, "y", make_variable(TYPE_STRING, true, true));
    symtable_insert(&table, "z", make_variable(TYPE_NULL, true, true));

    // Insert a function with 2 params
    Param *params = NULL;
    params = append_param(params, make_param("a", TYPE_NUM));
    params = append_param(params, make_param("b", TYPE_STRING));
    symtable_insert(&table, "foo", make_function(2, params, true));

    // Insert getter and setter
    symtable_insert(&table, "getVal", make_getter(TYPE_NUM, true));
    symtable_insert(&table, "setVal", make_setter(TYPE_STRING, true));

    printf("=== Inorder traversal of AVL symbol table ===\n");
    print_inorder(table.root);

    // Test search
    const char *search_key = "foo";
    SymTableData *found = symtable_search(&table, search_key);
    if (found) {
        printf("\nSearch: Key '%s' found, type=%d\n", search_key, found->type);
    } else {
        printf("\nSearch: Key '%s' NOT found\n", search_key);
    }

    // Clean up
    symtable_free(&table);

    return 0;
}
